#USER ---------------------------------------------------
ldapApprovalGroup: dev-ops-admin

#Deploy--------------------------------------------------------

approvalTimeout: 15
approvalTimeoutUnit: 'MINUTES'
abortReasonTimeout: 10
abortReasonTimeoutUnit: 'MINUTES'

#DeployApproval--------------------------------------------------------
ApprovalGroup: sony,admin
emailApprovalRecipients:  shanmugam.nsw@gmail.com
emailOutageRecipients: shanmugam.nsw@gmail.com

