#USER ---------------------------------------------------
ldapApprovalGroup: dev-ops-admin,admin

#Deploy--------------------------------------------------------

approvalTimeout: 15
approvalTimeoutUnit: 'MINUTES'
abortReasonTimeout: 10
abortReasonTimeoutUnit: 'MINUTES'

#DeployApproval--------------------------------------------------------
ldapApprovalGroup: sony
emailApprovalRecipients:  shanmugam.nsw@gmail.com
emailOutageRecipients: shanmugam.nsw@gmail.com

